# Plan 
1. Demographic Inforamtions 
2. Basic information regarding online class 
3. Physical and Mental Problems 
4. Perception on  onlinie class

In [3]:
import pandas as pd 
import researchpy as rp 
# https://researchpy.readthedocs.io/en/latest/

In [13]:
df = pd.read_excel("jnu_distance_learning.xlsx")

In [14]:
df.head()

,Timestamp,Are you willing to participate in this survey?,Are you a student of Jagannath University ?,Age:,Gender:,Faculty:,Department:,Department:.1,Do you agree-,Which type of platforms did you use?,...,How long have you been doing online classes?,Satisfactory level in online class:,Did you feel any mental disturbance during online class?,What kind of mental disturbance did you feel during online class?,Did you face any physical problem during online class?,What kind of physical problem did you face during online class?,How attentive do you think you were in the online classes ?,Do you prefer online classes over direct classes?,Your understanding level in Online class vs. Direct Class: [Online Class],Your understanding level in Online class vs. Direct Class: [Direct class]
0,2021-04-29 16:42:42.448,Yes,Yes,22.0,Female,Faculty of Life & Earth Science,Department of Biochemistry & Molecular Biology,NaN,Agree,Zoom,...,2 Semister,3.0,Yes,"Felt bored, Attention split, Depression, Mood ...",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
1,2021-04-30 22:18:36.884,Yes,Yes,22.0,Female,Faculty of Life & Earth Science,Department of Biochemistry & Molecular Biology,NaN,Agree,Google Meet,...,NaN,5.0,Yes,"Felt bored, Anxiety",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
2,2021-05-01 08:23:58.532,Yes,Yes,22.0,Female,Faculty of Life & Earth Science,Department of Microbiology,NaN,Agree,"Zoom, Google Meet",...,2 semester,3.0,Yes,"Felt bored, Attention split, Depression, Mood ...",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
3,2021-05-09 17:02:09.742,Yes,Yes,22.0,Male,Faculty of Life & Earth Science,Department of Microbiology,NaN,Agree,"Zoom, Google Meet",...,2 semester,5.0,Yes,"Felt bored, Attention split",Yes,"Back pain, Exhaustion",3.0,Yes,Avarage,good
4,2021-05-09 17:24:18.026,Yes,Yes,21.0,Female,Faculty of Life & Earth Science,Department of Microbiology,NaN,Agree,Zoom,...,2 semester,4.0,Yes,"Felt bored, Attention split, Anxiety, Monotonous",Yes,"Watery or dry eyes, Headache, Increased sensit...",8.0,No,Low,good

In [15]:
# columns 
df.columns

Index(['Timestamp', 'Are you willing to participate in this survey?',
       'Are you a student of Jagannath University ?', 'Age:', 'Gender:',
       'Faculty:', 'Department:', 'Department:.1', 'Do you agree-',
       'Which type of platforms  did you use?',
       'How long was the average class time?', 'Average classes per week:',
       'What is your preferred online class duration?',
       'How long have you been doing online classes?',
       'Satisfactory level in online class:',
       'Did you feel any mental disturbance during online class? ',
       'What kind of mental disturbance did you feel during online class?',
       'Did you face any physical  problem during online class? ',
       'What kind of physical problem  did you face during online class? ',
       'How attentive do you think you were in the online classes ?',
       'Do you prefer online classes over direct classes?',
       'Your understanding level in Online class vs. Direct Class: [Online Class]',
       'Your understanding level in Online class vs. Direct Class: [Direct class]'],
      dtype='object')

In [17]:
df['Are you willing to participate in this survey?'].value_counts()

Yes    153
No       4
Name: Are you willing to participate in this survey?, dtype: int64

In [18]:
df['Are you a student of Jagannath University ?'].value_counts()

Yes    150
No       7
Name: Are you a student of Jagannath University ?, dtype: int64

In [19]:
df.shape

(157, 23)

In [20]:
# Remove records of outside JnU 
df = df[(df['Are you willing to participate in this survey?'] == "Yes") & (df['Are you a student of Jagannath University ?'] == "Yes")]

In [21]:
df.shape

(146, 23)

In [22]:
df.drop(['Timestamp','Are you willing to participate in this survey?',
       'Are you a student of Jagannath University ?','Department:.1'], axis=1, inplace=True)

In [23]:
df.head()

,Age:,Gender:,Faculty:,Department:,Do you agree-,Which type of platforms did you use?,How long was the average class time?,Average classes per week:,What is your preferred online class duration?,How long have you been doing online classes?,Satisfactory level in online class:,Did you feel any mental disturbance during online class?,What kind of mental disturbance did you feel during online class?,Did you face any physical problem during online class?,What kind of physical problem did you face during online class?,How attentive do you think you were in the online classes ?,Do you prefer online classes over direct classes?,Your understanding level in Online class vs. Direct Class: [Online Class],Your understanding level in Online class vs. Direct Class: [Direct class]
0,22.0,Female,Faculty of Life & Earth Science,Department of Biochemistry & Molecular Biology,Agree,Zoom,1.0,3.0,45 - 60 minutes,2 Semister,3.0,Yes,"Felt bored, Attention split, Depression, Mood ...",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
1,22.0,Female,Faculty of Life & Earth Science,Department of Biochemistry & Molecular Biology,Agree,Google Meet,3.0,16.0,45 - 60 minutes,NaN,5.0,Yes,"Felt bored, Anxiety",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
2,22.0,Female,Faculty of Life & Earth Science,Department of Microbiology,Agree,"Zoom, Google Meet",4.0,3.0,45 - 60 minutes,2 semester,3.0,Yes,"Felt bored, Attention split, Depression, Mood ...",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
3,22.0,Male,Faculty of Life & Earth Science,Department of Microbiology,Agree,"Zoom, Google Meet",1.5 Hours,20.0,45 - 60 minutes,2 semester,5.0,Yes,"Felt bored, Attention split",Yes,"Back pain, Exhaustion",3.0,Yes,Avarage,good
4,21.0,Female,Faculty of Life & Earth Science,Department of Microbiology,Agree,Zoom,2 Hours,14.0,45 - 60 minutes,2 semester,4.0,Yes,"Felt bored, Attention split, Anxiety, Monotonous",Yes,"Watery or dry eyes, Headache, Increased sensit...",8.0,No,Low,good

# Exporting Clean Data

In [69]:
df.to_csv('jnu_distance_learning_cleaned.csv', index=False)

In [25]:
data = pd.read_csv('jnu_distance_learning_cleaned.csv')

In [26]:
data.head()

,Age:,Gender:,Faculty:,Department:,Do you agree-,Which type of platforms did you use?,How long was the average class time?,Average classes per week:,What is your preferred online class duration?,How long have you been doing online classes?,Satisfactory level in online class:,Did you feel any mental disturbance during online class?,What kind of mental disturbance did you feel during online class?,Did you face any physical problem during online class?,What kind of physical problem did you face during online class?,How attentive do you think you were in the online classes ?,Do you prefer online classes over direct classes?,Your understanding level in Online class vs. Direct Class: [Online Class],Your understanding level in Online class vs. Direct Class: [Direct class]
0,22.0,Female,Faculty of Life & Earth Science,Department of Biochemistry & Molecular Biology,Agree,Zoom,1.0,3.0,45 - 60 minutes,2 Semister,3.0,Yes,"Felt bored, Attention split, Depression, Mood ...",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
1,22.0,Female,Faculty of Life & Earth Science,Department of Biochemistry & Molecular Biology,Agree,Google Meet,3.0,16.0,45 - 60 minutes,NaN,5.0,Yes,"Felt bored, Anxiety",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
2,22.0,Female,Faculty of Life & Earth Science,Department of Microbiology,Agree,"Zoom, Google Meet",4.0,3.0,45 - 60 minutes,2 semester,3.0,Yes,"Felt bored, Attention split, Depression, Mood ...",Yes,"Sore, tiredness in eye, burning or itching eye...",NaN,NaN,NaN,NaN
3,22.0,Male,Faculty of Life & Earth Science,Department of Microbiology,Agree,"Zoom, Google Meet",1.5 Hours,20.0,45 - 60 minutes,2 semester,5.0,Yes,"Felt bored, Attention split",Yes,"Back pain, Exhaustion",3.0,Yes,Avarage,good
4,21.0,Female,Faculty of Life & Earth Science,Department of Microbiology,Agree,Zoom,2 Hours,14.0,45 - 60 minutes,2 semester,4.0,Yes,"Felt bored, Attention split, Anxiety, Monotonous",Yes,"Watery or dry eyes, Headache, Increased sensit...",8.0,No,Low,good

In [70]:
data.columns

Index(['Age:', 'Gender:', 'Faculty:', 'Department:', 'Do you agree-',
       'Which type of platforms  did you use?',
       'How long was the average class time?', 'Average classes per week:',
       'What is your preferred online class duration?',
       'How long have you been doing online classes?',
       'Satisfactory level in online class:',
       'Did you feel any mental disturbance during online class? ',
       'What kind of mental disturbance did you feel during online class?',
       'Did you face any physical  problem during online class? ',
       'What kind of physical problem  did you face during online class? ',
       'How attentive do you think you were in the online classes ?',
       'Do you prefer online classes over direct classes?',
       'Your understanding level in Online class vs. Direct Class: [Online Class]',
       'Your understanding level in Online class vs. Direct Class: [Direct class]'],
      dtype='object')

# Demographics Summary

In [28]:
rp.codebook(data['Age:'])

Variable: Age:    Data Type: float64

 Number of Obs.: 146
 Number of missing obs.: 0
 Percent missing: 0.0
 Number of unique values: 8

 Range: [18.0, 25.0]
 Mean: 21.55
 Standard Deviation: 1.47
 Mode: 21.0
 10th Percentile: 20.0
 25th Percentile: 21.0
 50th Percentile: 21.0
 75th Percentile: 22.75
 90th Percentile: 24.0

In [71]:
rp.summary_cat(data['Gender:'])

  Variable Outcome  Count  Percent
0  Gender:    Male     76    52.05
1           Female     70    47.95

# Perception of Distance Learning

In [ ]:
,
       ,
      ,
       'What is your preferred online class duration?',
       'How long have you been doing online classes?',
       'Satisfactory level in online class:',

In [72]:
# agree with the defination of distance learning 
rp.summary_cat(data['Do you agree-'])

,Variable,Outcome,Count,Percent
0,Do you agree-,Agree,130,89.04
1,,Disagree,14,9.59
2,,Pretty much,1,0.68
3,,"By maintaining health tips, offline class is m...",1,0.68

In [75]:
x = data['Which type of platforms  did you use?'].str.get_dummies(sep=',')
x

,GoToMeetings,Google Meet,Skype,Whats app Messanger,YouTube,Google Meet,Zoom,Zoom & Google Meet
0,0,0,0,0,0,0,1,0
1,0,0,0,0,0,1,0,0
2,0,1,0,0,0,0,1,0
3,0,1,0,0,0,0,1,0
4,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...
141,0,0,0,0,0,0,1,0
142,0,0,0,0,0,1,0,0
143,0,0,0,0,0,0,1,0
144,0,0,0,0,0,0,1,0
145,0,1,1,1,0,0,1,0

In [78]:
x['Zoom'].value_counts()

1    139
0      7
Name: Zoom, dtype: int64

In [74]:
# types of platforms that students used 
rp.summary_cat(data['Which type of platforms  did you use?'])

,Variable,Outcome,Count,Percent
0,Which type of platforms did you use?,Zoom,103,70.55
1,,"Zoom, Google Meet",26,17.81
2,,Google Meet,6,4.11
3,,"Zoom, Skype, Google Meet",5,3.42
4,,"Zoom, Skype",2,1.37
5,,"Zoom, YouTube",1,0.68
6,,"Zoom, Skype, Google Meet, GoToMeetings",1,0.68
7,,Zoom & Google Meet,1,0.68
8,,"Zoom, Skype, Google Meet, Whats app Messanger",1,0.68

In [35]:
rp.summary_cat(df['How long was the average class time?'])

                               Variable    Outcome  Count  Percent
0  How long was the average class time?    1 Hours     90    61.64
1                                        1.5 Hours     39    26.71
2                                          2 Hours     11     7.53
3                                        2.5 Hours      3     2.05
4                                              1.0      1     0.68
5                                              3.0      1     0.68
6                                              4.0      1     0.68

In [36]:
rp.summary_cat(df['Average classes per week:'])

                     Variable  Outcome  Count  Percent
0   Average classes per week:      3.0     25    17.12
1                                  4.0     20    13.70
2                                  2.0     17    11.64
3                                 10.0     12     8.22
4                                  6.0     11     7.53
5                                  7.0      9     6.16
6                                  5.0      9     6.16
7                                 12.0      9     6.16
8                                  1.0      7     4.79
9                                  8.0      6     4.11
10                                16.0      4     2.74
11                                14.0      4     2.74
12                                15.0      4     2.74
13                                18.0      3     2.05
14                                 9.0      2     1.37
15                                20.0      2     1.37
16                                22.0      1     0.68
17                                 0.0      1     0.68

In [31]:
df.columns

Index(['Age:', 'Gender:', 'Faculty:', 'Department:', 'Do you agree-',
       'Which type of platforms  did you use?',
       'How long was the average class time?', 'Average classes per week:',
       'What is your preferred online class duration?',
       'How long have you been doing online classes?',
       'Satisfactory level in online class:',
       'Did you feel any mental disturbance during online class? ',
       'What kind of mental disturbance did you feel during online class?',
       'Did you face any physical  problem during online class? ',
       'What kind of physical problem  did you face during online class? ',
       'How attentive do you think you were in the online classes ?',
       'Do you prefer online classes over direct classes?',
       'Your understanding level in Online class vs. Direct Class: [Online Class]',
       'Your understanding level in Online class vs. Direct Class: [Direct class]'],
      dtype='object')

# Mental Health

In [66]:
rp.summary_cat(df['Did you feel any mental disturbance during online class? '])

                                            Variable Outcome  Count  Percent
0  Did you feel any mental disturbance during onl...     Yes    101    69.18
1                                                         No     45    30.82

In [67]:
mental_pb = df['What kind of mental disturbance did you feel during online class?'].str.get_dummies(sep=',')

In [24]:
rp.summary_cat(data[['Did you feel any mental disturbance during online class? ', 
                    'What kind of mental disturbance did you feel during online class?']])

,Variable,Outcome,Count,Percent
0,Did you feel any mental disturbance during onl...,Yes,89,69.53
1,,No,39,30.47
2,What kind of mental disturbance did you feel d...,Attention split,28,31.46
3,,Felt bored,11,12.36
4,,"Felt bored, Attention split, Monotonous, Mood ...",5,5.62
5,,"Felt bored, Attention split, Anxiety, Depressi...",5,5.62
6,,"Felt bored, Attention split",5,5.62
7,,Monotonous,3,3.37
8,,"Felt bored, Attention split, Anxiety, Depressi...",3,3.37
9,,"Felt bored, Attention split, Monotonous",3,3.37
10,,"Felt bored, Attention split, Anxiety, Mood swing",2,2.25
11,,Depression,2,2.25
12,,"Felt bored, Attention split, Depression",2,2.25
13,,"Felt bored, Anxiety, Mood swing",2,2.25
14,,"Felt bored, Attention split, Anxiety, Monotono...",2,2.25
15,,"Felt bored, Attention split, Depression, Mood ...",2,2.25
16,,Mood swing,1,1.12
17,,"Felt bored, Anxiety",1,1.12
18,,"Felt bored, Attention split, Anxiety",1,1.12
19,,"Felt bored, Monotonous, long time class is bad...",1,1.12
20,,"Felt bored, Attention split, Anxiety, Depressi...",1,1.12
21,,"Attention split, Anxiety, Depression, Mood swing",1,1.12
22,,"Attention split, Anxiety, Depression, Monotono...",1,1.12
23,,Network problem,1,1.12
24,,"Felt bored, Attention split, Anxiety, Depression",1,1.12
25,,Headache,1,1.12
26,,"Felt bored, Anxiety, Depression, Mood swing",1,1.12
27,,"Attention split, Anxiety",1,1.12
28,,"Felt bored, Attention split, Anxiety, Monotonous",1,1.12
29,,Anxiety,1,1.12

# Physical Problems

In [25]:
data['Did you face any physical  problem during online class? '].value_counts()

No     74
Yes    54
Name: Did you face any physical  problem during online class? , dtype: int64

In [26]:
data['Did you face any physical  problem during online class? '].value_counts(normalize=True) *100

No     57.8125
Yes    42.1875
Name: Did you face any physical  problem during online class? , dtype: float64

In [27]:
rp.summary_cat(data['Did you face any physical  problem during online class? '])

                                            Variable Outcome  Count  Percent
0  Did you face any physical  problem during onli...      No     74    57.81
1                                                        Yes     54    42.19

In [28]:
rp.summary_cat(data[['Did you face any physical  problem during online class? ',
                    'What kind of physical problem  did you face during online class? ']])

,Variable,Outcome,Count,Percent
0,Did you face any physical problem during onli...,No,74,57.81
1,,Yes,54,42.19
2,What kind of physical problem did you face du...,Headache,4,7.41
3,,"Tiredness in eye, Headache",3,5.56
4,,"Tiredness in eye, Burning or itching eyes, Blu...",2,3.70
5,,"Tiredness in eye, Burning or itching eyes, Wat...",2,3.70
6,,"Tiredness in eye, Headache, Increased sensitiv...",2,3.70
7,,Tiredness in eye,2,3.70
8,,Feeling that you cannot keep your eyes open,2,3.70
9,,"Tiredness in eye, Headache, Back pain, Neck pa...",2,3.70
10,,Back pain,2,3.70
11,,"Headache, Increased sensitivity to light, Back...",1,1.85
12,,"Burning or itching eyes, Watery or dry eyes, H...",1,1.85
13,,"Tiredness in eye, Watery or dry eyes, Headache...",1,1.85
14,,"Sore, tiredness in eye, burning or itching eye...",1,1.85
15,,"Tiredness in eye, Burning or itching eyes, Wat...",1,1.85
16,,"Tiredness in eye, Headache, Feeling that you c...",1,1.85
17,,"Tiredness in eye, Headache, Back pain, Neck pa...",1,1.85
18,,Burning or itching eyes,1,1.85
19,,"Tiredness in eye, Burning or itching eyes, Wat...",1,1.85
20,,Multiple symptoms of migraine,1,1.85
21,,"Tiredness in eye, Burning or itching eyes, Wat...",1,1.85
22,,"Tiredness in eye, Headache, Feeling that you c...",1,1.85
23,,Shoulder ache,1,1.85
24,,"Tiredness in eye, Watery or dry eyes, Blurred ...",1,1.85
25,,"Sore, tiredness in eye, burning or itching eye...",1,1.85
26,,"Increased sensitivity to light, Neck pain",1,1.85
27,,"Tiredness in eye, Burning or itching eyes, Hea...",1,1.85
28,,"Tiredness in eye, Watery or dry eyes, Headache...",1,1.85
29,,"Sore, tiredness in eye, burning or itching eye...",1,1.85
30,,"Tiredness in eye, Blurred or double vision, He...",1,1.85
31,,"Tiredness in eye, Watery or dry eyes, Headache...",1,1.85
32,,"Tiredness in eye, Headache, Neck pain",1,1.85
33,,"Tiredness in eye, Watery or dry eyes, Headache...",1,1.85
34,,"Tiredness in eye, Burning or itching eyes, Blu...",1,1.85
35,,"Tiredness in eye, Headache, Increased sensitiv...",1,1.85
36,,"Watery or dry eyes, Headache, Increased sensit...",1,1.85
37,,"Tiredness in eye, Watery or dry eyes, Headache...",1,1.85
38,,"Tiredness in eye, Watery or dry eyes, Blurred ...",1,1.85
39,,"Tiredness in eye, Burning or itching eyes, Hea...",1,1.85
40,,"Tiredness in eye, Headache, Back pain, Shoulde...",1,1.85
41,,"Tiredness in eye, Burning or itching eyes, Wat...",1,1.85
42,,"Tiredness in eye, Headache, Back pain",1,1.85
43,,"Back pain, Exhaustion",1,1.85